version: 2.1
defaults: &defaults
  docker:
  - image: circleci/node:10.14.1
  working_directory: ~/project
#####################################################
# Commands
#####################################################
commands:
  check_result:
    description: Get last command result
    parameters:
      step_name:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: |
            RESULT=$?
            if [ $RESULT != 0 ];
            then
              echo 'Test failed'
              exit 1
            else
              echo 'Test passed'
              exit 0
            fi
#####################################################
# Jobs
#####################################################
jobs:
  dependencies_install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run:
          name: Dependencies Install
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
          - ./
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build System
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
          - ./

  post-storybook-link-to-github:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - checkout
      - run:
          command: bin/post-storybook-link-to-github
          name:
            Post link to storybook as a Github comment on the PR

  build-storybook:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: yarn && yarn build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - symphony-bdk-ui-toolkit/storybook-static

  deploy-storybook:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to Symphony S3
          command:
            aws s3 --region "us-east-1" sync --acl public-read
            symphony-bdk-ui-toolkit/storybook-static
            s3://symphony--rfq--storybook-demo-site/bdk-ui-toolkit/${CIRCLE_SHA1}

#####################################################
# Workflow
#####################################################
workflows:
  version: 2
  check_package:
    jobs:
      - dependencies_install
      - build:
          requires:
            - dependencies_install
      - build-storybook
      - deploy-storybook:
          requires:
            - build-storybook
      - post-storybook-link-to-github:
          requires:
            - deploy-storybook
#      - notify-about-storybook-deployment:
#          requires:
#            - deploy-storybook
#          filters:
#            branches:
#              only:
#                - develop
#                - migration/develop