import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-viewport/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-a11y';
import 'storybook-addon-specifications/register';
import 'storybook-addon-jsx/register';
import 'storybook-addon-react-live-edit/dist/register';
import 'storybook-addon-styled-component-theme/dist/src/register';
